### ISSUE TITLE
Configure Travis to upload release apks back to GitHub

### ISSUE THREAD

**Issue by larsgrefer** [pockethub/PocketHub#770]
Configure Travis to attatch the builded apk of every tag as binary to the corresponding GitHub release as described here: http://docs.travis-ci.com/user/deployment/releases/

An App implementing this can be found here: https://github.com/larsgrefer/bpm-meter-android

**Comment by hzsweers** [comment]
@larsgrefer could you give a more thorough breakdown of how the `deploy` segment of that project's `.travis.yml` works? Also, I don't think having an API key in public like that is going to fly for this project.

**Comment by larsgrefer** [comment]
@hzsweers I hope this helps:
```yml
deploy:
  # Deploy the file(s) to the github release (other targets like amazon-aws or npm can be found here: http://docs.travis-ci.com/user/deployment/ )
  provider: releases
  # The oauth token for github (used by travis to upload the file(s) to github)
  api_key:
    # The api-key is encrypted like described here: http://docs.travis-ci.com/user/encryption-keys/  (only travis can decrypt the key)
    secure: X9fnLUh/qKVwtDOFicmHBZN3r0sEnM3kp4st/vjRCuDgTV30pG/0y3kjnbSuRm/Qgw8sgvzD5RlGQ7aHiU6naJnlrAbBeHVs3EECMvRc2zZjeUGCg4Iwtd0rPnvl2X28jOFTOeOM24FP6cqhVK/keilLcTCjB4llTYjbV4FkIqo=
  # Which file(s) to upload
  file: app/build/outputs/apk/app-release.apk
  # do not delete the files we're trying to upload
  skip_cleanup: true
  # only deploy if
  on:
    # we are on this repo
    repo: larsgrefer/bpm-meter-android
    # and we are building a tag
    tags: true
```

The API key should not be a problem, because in fact its not public. It's encrypted with an key-pair and only travis can decrypt it and only will do it on trusted builds (not on forks and not on pull-requests)

The whole thing can only be set up by someone with write access to this repository, because the oauth token must be created
